# ==========================================
# AUTO GENERATED CONF.PY
# DO NOT EDIT — generated by gen_conf.py
# ==========================================

from pathlib import Path
import sys
from jinja2 import Template

# ---------------------------------------------------------
# 【1】路径初始化
# ---------------------------------------------------------
THIS_FILE = Path(__file__).resolve()
PROJECT_ROOT = THIS_FILE.parents[4]     # docs/<lang>/<product>/source/conf.py
TOOLS_DIR = PROJECT_ROOT / "tools"

sys.path.insert(0, str(PROJECT_ROOT))
sys.path.insert(0, str(TOOLS_DIR))

from tools.utils import path_utils as paths


# ---------------------------------------------------------
# 【2】基础参数
# ---------------------------------------------------------
LANG       = "zh_cn"
PRODUCT    = "N706B"
DOC_TYPE   = "AT"
PDF_THEME  = "neoway_default"     # 当前 product 的主题名称（来自 config.yaml）


# ---------------------------------------------------------
# 【3】加载语言包
# ---------------------------------------------------------
lang_file = paths.ROOT / "docs/_langs/zh_cn.py"
exec(open(lang_file, "r", encoding="utf-8").read(), globals())


# ---------------------------------------------------------
# 【4】加载通用配置（extensions / latex_elements等）
# ---------------------------------------------------------
COMMON_CONF = paths.ROOT / "docs" / "_common" / "conf_common.py"
exec(COMMON_CONF.read_text(encoding="utf-8"), globals())


# ---------------------------------------------------------
# 【5】加载主题（theme.yaml）
# ---------------------------------------------------------
theme_cfg = paths.load_pdf_theme_cfg(PDF_THEME) or {}

title_color   = theme_cfg.get("title_color",  [0, 0, 0])
header_color  = theme_cfg.get("header_color", [0, 0, 0])
footer_color  = theme_cfg.get("footer_color", [0, 0, 0])
tikz_bg       = theme_cfg.get("tikz_background", False)

bg_file = theme_cfg.get("cover_background", "")


# ---------------------------------------------------------
# 【6】主题路径
# ---------------------------------------------------------
PDF_THEME_ROOT = paths.pdf_theme_root() / PDF_THEME


# ---------------------------------------------------------
# 【7】封面背景图路径
# ---------------------------------------------------------
if bg_file:
    COVER_BG_LATEX = (PDF_THEME_ROOT / "_static" / bg_file).as_posix()
else:
    COVER_BG_LATEX = ""


# ---------------------------------------------------------
# 【8】渲染 cover.tex —— 写入 Sphinx latex 输出目录
# ---------------------------------------------------------
LATEX_OUT = Path(__file__).parent.parent / "build" / "pdf"
LATEX_OUT.mkdir(parents=True, exist_ok=True)

template_path = PDF_THEME_ROOT / "cover_template.tex.j2"
output_path   = LATEX_OUT / "cover.tex"

HEADER_LOGO = (PDF_THEME_ROOT / "_static" / "header-logo.png").as_posix()

context = {
    "product": PRODUCT,
    "title": PROJECT_TITLE,
    "issue": ISSUE,
    "date": DATE,
    "cover_background": COVER_BG_LATEX,
    "header_logo": HEADER_LOGO,
    "company_name": footer_text,

    # ★ 来自 theme.yaml
    "title_color": title_color,
    "header_color": header_color,
    "footer_color": footer_color,
    "tikz_background": tikz_bg,
}

tpl = Template(template_path.read_text(encoding="utf-8"))
output_path.write_text(tpl.render(**context), encoding="utf-8")

print(f"[COVER] Rendered cover from theme '{PDF_THEME}' → {output_path}")