# ==========================================
# AUTO GENERATED CONF.PY
# DO NOT EDIT — generated by gen_conf.py
# ==========================================

from pathlib import Path
import sys

THIS_FILE = Path(__file__).resolve()
PROJECT_ROOT = THIS_FILE.parents[4]

sys.path.insert(0, str(PROJECT_ROOT))
sys.path.insert(0, str(PROJECT_ROOT / "tools"))

import tools.utils.path_utils as paths

LANG = "en"
PRODUCT = "N706B"
DOC_TYPE = "AT"

# 载入语言包
exec(open(PROJECT_ROOT / "docs/_langs/en.py", "r", encoding="utf-8").read(), globals())

# 引入公共配置
COMMON_CONF = PROJECT_ROOT / "docs" / "_common" / "conf_common.py"
exec(COMMON_CONF.read_text(encoding="utf-8"), globals())