# ==========================================
# AUTO GENERATED CONF.PY
# DO NOT EDIT — generated by gen_conf.py
# ==========================================

from pathlib import Path
import sys

# ---------------------------------------------------------
# 【1】加载 path_utils（核心路径体系）
# ---------------------------------------------------------
THIS_FILE = Path(__file__).resolve()
PROJECT_ROOT = THIS_FILE.parents[4]

TOOLS_DIR = PROJECT_ROOT / "tools"
sys.path.insert(0, str(PROJECT_ROOT))
sys.path.insert(0, str(TOOLS_DIR))

try:
    from tools.utils import path_utils as paths
    ROOT = paths.ROOT
except:
    ROOT = PROJECT_ROOT

# ---------------------------------------------------------
# 【2】基础参数
# ---------------------------------------------------------
LANG     = "en"
PRODUCT  = "N706B"
DOC_TYPE = "AT"

# ---------------------------------------------------------
# 【3】加载语言包
# ---------------------------------------------------------
lang_file = ROOT / "docs/_langs/en.py"
exec(open(lang_file, "r", encoding="utf-8").read(), globals())

# ---------------------------------------------------------
# 【4】继承通用配置
# ---------------------------------------------------------
COMMON_CONF = ROOT / "docs" / "_common" / "conf_common.py"
exec(COMMON_CONF.read_text(encoding="utf-8"), globals())

# ---------------------------------------------------------
# 【5】标题覆盖
# ---------------------------------------------------------
project     = PROJECT_TITLE
html_title  = PROJECT_TITLE
author      = "Neoway Technology"

latex_documents = [
    (
        "index",
        f"{PRODUCT}_{DOC_TYPE}.tex",
        PROJECT_TITLE,
        author,
        "manual",
    )
]

# ---------------------------------------------------------
# 【6】解析封面背景图（强制 POSIX）
# ---------------------------------------------------------
cover_cfg = paths.config["common"].get("cover_background", {})
bg_filename = cover_cfg.get(PRODUCT, cover_cfg.get("default", "background.png"))
COVER_BG_LATEX = (paths.static_images_path() / bg_filename).as_posix()

# ---------------------------------------------------------
# 【7】渲染封面 cover.tex
# ---------------------------------------------------------
template_path = paths.latex_common_path() / "cover_template.tex.j2"
output_path   = paths.latex_common_path() / "cover.tex"

template_path = Path(template_path)
output_path   = Path(output_path)

from jinja2 import Template

context = {
    "product": PRODUCT,
    "title": PROJECT_TITLE,
    "issue": ISSUE,
    "date": DATE,
    "cover_background": COVER_BG_LATEX,
}

tpl = Template(template_path.read_text(encoding="utf-8"))
output_path.write_text(tpl.render(**context), encoding="utf-8")

print(f"[COVER] Rendered cover → {output_path}")