import platform
from pathlib import Path
from tools.utils import path_utils as paths

def generate_fonts_tex():
    cfg = paths.config
    os_name = platform.system().lower()

    # 映射为 config.yaml 字段
    if "windows" in os_name:
        key = "windows"
    elif "darwin" in os_name:
        key = "mac"
    else:
        key = "linux"

    font_cfg = cfg["fonts"][key]

    cjk = font_cfg["cjk"]
    sans = font_cfg["sans"]
    mono = font_cfg["mono"]

    fonts_tex = f"""
% ========== AUTO GENERATED by generate_fonts_tex.py ==========
% Do NOT edit manually

\\usepackage{{xeCJK}}
\\usepackage{{fontspec}}

% ---- Western Fonts ----
\\setmainfont{{Times New Roman}}
\\setsansfont{{{sans}}}
\\setmonofont{{{mono}}}

% ---- CJK Fonts (Platform Auto Selected) ----
\\setCJKmainfont{{{cjk}}}
\\setCJKsansfont{{{cjk}}}
\\setCJKmonofont{{{cjk}}}

% ---- fallback ----
\\defaultCJKfontfeatures{{
    Script=Hans,
    Language=Chinese
}}
    """

    out_path = paths.latex_theme_path() / "fonts.tex"
    out_path.write_text(fonts_tex, encoding="utf-8")
    print(f"[FONTS] Generated fonts.tex ({key}) → {out_path}")
