# tools/latex_inject.py
from datetime import datetime

def get_latex_block(TITLE, AUTHOR, SUBJECT, zh_font, mono_font, cover_block):
    # 用纯拼接字符串方式避免 Python 提前解释 {}
    date_now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    block = (
        "# >>> BEGIN: NEOWAY_LATEX_BLOCK\n"
        f"# 自动注入时间：{date_now}\n"
        "latex_engine = 'xelatex'\n"
        "latex_additional_files = [\n"
        "    '../../_common/_static/logo.png',\n"
        "    '../../_common/_static/background.png',\n"
        "    '../../_common/_static/header-logo.png'\n"
        "]\n"
        f"latex_documents = [('index', 'Neoway_Manual.tex', '{TITLE}', '{AUTHOR}', 'manual')]\n\n"
        "latex_elements = globals().get('latex_elements', {})\n\n"
        "latex_elements.update({\n"
        "    'papersize': 'a4paper',\n"
        "    'pointsize': '11pt',\n"
        "    'extraclassoptions': 'openany,oneside',\n"
        "    'geometry': r'\\usepackage[a4paper,top=22mm,bottom=22mm,left=22mm,right=22mm,headheight=18pt]{geometry}',\n"
        "    'fontpkg': r'''\n"
        "        \\usepackage{xeCJK}\n"
        f"        \\setCJKmainfont{{{zh_font}}}\n"
        "        \\setmainfont{Times New Roman}\n"
        "        \\setsansfont{Arial}\n"
        f"        \\setmonofont{{{mono_font}}}\n"
        "    ''',\n"
        "    'preamble': r'''\n"
        "        \\usepackage{graphicx,tikz,eso-pic,xcolor,fancyhdr,titlesec,hyperref}\n"
        "        \\graphicspath{{./}{../../_common/_static/}{_common/_static/}}\n"
        "        \\setlength{\\headheight}{24pt}\n"
        "        \\setlength{\\headsep}{12pt}\n"
        "        \\hypersetup{ pdftitle={ " + TITLE + " }, pdfauthor={ " + AUTHOR + " }, pdfsubject={ " + SUBJECT + " }, colorlinks=true, linkcolor=blue, urlcolor=blue }\n"
        "        \\newcommand{\\neowayheaderlogo}{\\includegraphics[scale=0.25]{header-logo.png}}\n"
        "        \\makeatletter\n"
        "        \\renewcommand{\\chaptermark}[1]{\\markboth{#1}{}}\n"
        "        \\renewcommand{\\sectionmark}[1]{\\markright{#1}}\n"
        "        \\makeatother\n"
        "        \\fancypagestyle{normal}{%\n"
        "            \\fancyhf{}\n"
        "            \\fancyhead[L]{\\neowayheaderlogo}\n"
        "            \\fancyhead[R]{\\nouppercase{\\rightmark}}\n"
        "            \\fancyfoot[L]{深圳市有方科技股份有限公司版权所有}\n"
        "            \\fancyfoot[R]{\\thepage}\n"
        "            \\renewcommand{\\headrulewidth}{0.4pt}\n"
        "            \\renewcommand{\\footrulewidth}{0.4pt}\n"
        "        }\n"
        "        \\fancypagestyle{plain}{%\n"
        "            \\fancyhf{}\n"
        "            \\fancyhead[L]{\\neowayheaderlogo}\n"
        "            \\fancyhead[R]{\\nouppercase{\\rightmark}}\n"
        "            \\fancyfoot[L]{深圳市有方科技股份有限公司版权所有}\n"
        "            \\fancyfoot[R]{\\thepage}\n"
        "            \\renewcommand{\\headrulewidth}{0.4pt}\n"
        "            \\renewcommand{\\footrulewidth}{0.4pt}\n"
        "        }\n"
        "        \\let\\cleardoublepage\\clearpage\n"
        "    ''',\n"
        f"    'maketitle': r'''{cover_block}'''\n"
        "})\n"
        "# <<< END:  NEOWAY_LATEX_BLOCK\n"
    )
    return block
